#!/bin/bash

# Essential GitHub Secrets Setup
# Only the 8 secrets required BEFORE infrastructure creation
# All other secrets will be auto-generated by Terraform workflows

set -e

echo "========================================="
echo "Essential Secrets Setup"
echo "========================================="
echo ""
echo "This script will set up the 8 essential secrets needed"
echo "before creating infrastructure."
echo ""
echo "The following will be AUTO-GENERATED later:"
echo "  • VITE_API_BASE_URL"
echo "  • CORS_ALLOWED_ORIGINS"
echo "  • DB_URL"
echo "  • VITE_API_BASE_URL_TESTING"
echo "  • JWT_SECRET"
echo ""
echo "========================================="
echo ""

# Check if git is installed
if ! command -v git &> /dev/null; then
    echo "❌ Git is not installed"
    echo "Install it from: https://git-scm.com/"
    exit 1
fi

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) is not installed"
    echo "Install it from: https://cli.github.com/"
    echo ""
    echo "Or install via Homebrew:"
    echo "  brew install gh"
    exit 1
fi

# Check if user is authenticated
if ! gh auth status &> /dev/null; then
    echo "❌ Not authenticated with GitHub CLI"
    echo "Run: gh auth login"
    exit 1
fi

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "❌ Not in a git repository"
    echo "Run: git init"
    exit 1
fi

echo "✅ Git and GitHub CLI are ready"
echo ""

# Function to set secret
set_secret() {
    local secret_name=$1
    local secret_value=$2
    
    if [ -z "$secret_value" ]; then
        echo "⏭️  Skipping $secret_name (empty value)"
        return
    fi
    
    echo "Setting $secret_name..."
    echo "$secret_value" | gh secret set "$secret_name"
    echo "✅ $secret_name set"
}

# Function to prompt for secret
prompt_secret() {
    local secret_name=$1
    local description=$2
    local is_password=$3
    
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Secret: $secret_name"
    echo "Description: $description"
    
    if [ "$is_password" = "true" ]; then
        read -sp "Enter value (hidden): " value
        echo ""
    else
        read -p "Enter value: " value
    fi
    
    if [ -n "$value" ]; then
        set_secret "$secret_name" "$value"
    else
        echo "❌ Error: This secret is required!"
        exit 1
    fi
}

echo "========================================="
echo "1. AWS CREDENTIALS"
echo "========================================="

prompt_secret "AWS_ACCESS_KEY_ID" "Your AWS Access Key ID" false
prompt_secret "AWS_SECRET_ACCESS_KEY" "Your AWS Secret Access Key" true

echo ""
echo "========================================="
echo "2. PRODUCTION DATABASE CREDENTIALS"
echo "========================================="

prompt_secret "DB_USERNAME" "Production database username (e.g., postgres)" false
prompt_secret "DB_PASSWORD" "Production database password (min 8 chars)" true

echo ""
echo "========================================="
echo "3. TESTING DATABASE CREDENTIALS"
echo "========================================="

prompt_secret "DB_USERNAME_TESTING" "Testing database username (e.g., postgres)" false
prompt_secret "DB_PASSWORD_TESTING" "Testing database password (min 8 chars)" true

echo ""
echo "========================================="
echo "4. S3 BUCKET NAMES (Must be globally unique)"
echo "========================================="
echo ""
echo "💡 Tip: Add your AWS account ID to make it unique"
echo "   Example: certcook-frontend-prod-989080044677"
echo ""

prompt_secret "S3_BUCKET_NAME" "Production S3 bucket name" false
prompt_secret "S3_BUCKET_NAME_TESTING" "Testing S3 bucket name" false

echo ""
echo "========================================="
echo "5. GITHUB PERSONAL ACCESS TOKEN (PAT)"
echo "========================================="
echo ""
echo "📝 PAT_TOKEN is used to auto-update secrets after infrastructure creation"
echo ""
echo "How to create PAT:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Select scopes: 'repo' and 'workflow'"
echo "4. Copy the token (starts with ghp_)"
echo ""
echo "⚠️  Without PAT_TOKEN, you'll need to manually update secrets"
echo "   after infrastructure creation."
echo ""

read -p "Do you want to set PAT_TOKEN now? (y/n): " set_pat

if [ "$set_pat" = "y" ] || [ "$set_pat" = "Y" ]; then
    prompt_secret "PAT_TOKEN" "GitHub Personal Access Token (ghp_...)" true
    echo ""
    echo "✅ PAT_TOKEN configured - secrets will auto-update!"
else
    echo ""
    echo "⏭️  Skipped PAT_TOKEN"
    echo "   You can set it later with:"
    echo "   gh secret set PAT_TOKEN --body \"ghp_your_token\""
fi

echo ""
echo "========================================="
echo "✅ ESSENTIAL SECRETS CONFIGURED!"
echo "========================================="
echo ""
echo "Essential secrets configured:"
echo "  ✅ AWS_ACCESS_KEY_ID"
echo "  ✅ AWS_SECRET_ACCESS_KEY"
echo "  ✅ DB_USERNAME"
echo "  ✅ DB_PASSWORD"
echo "  ✅ DB_USERNAME_TESTING"
echo "  ✅ DB_PASSWORD_TESTING"
echo "  ✅ S3_BUCKET_NAME"
echo "  ✅ S3_BUCKET_NAME_TESTING"

if [ "$set_pat" = "y" ] || [ "$set_pat" = "Y" ]; then
    echo "  ✅ PAT_TOKEN"
else
    echo "  ⏭️  PAT_TOKEN (skipped)"
fi
echo ""
echo "========================================="
echo "CREATING BRANCHES"
echo "========================================="
echo ""

# Check if branches exist, create if not
BRANCHES=("dev" "qa" "pre-prod" "prod")
CURRENT_BRANCH=$(git branch --show-current)

echo "Creating required branches..."
for branch in "${BRANCHES[@]}"; do
    if git show-ref --verify --quiet refs/heads/$branch; then
        echo "  ✅ Branch '$branch' already exists"
    else
        echo "  📝 Creating branch '$branch'..."
        git branch $branch 2>/dev/null || echo "  ⚠️  Could not create branch '$branch'"
    fi
done

echo ""
echo "Pushing branches to remote..."
for branch in "${BRANCHES[@]}"; do
    if git show-ref --verify --quiet refs/heads/$branch; then
        echo "  📤 Pushing '$branch' to remote..."
        git push origin $branch 2>/dev/null && echo "  ✅ Pushed '$branch'" || echo "  ⚠️  Could not push '$branch' (may already exist on remote)"
    fi
done

# Return to original branch
git checkout $CURRENT_BRANCH 2>/dev/null

echo ""
echo "✅ All branches created and pushed!"
echo ""
echo "========================================="
echo "NEXT STEPS"
echo "========================================="
echo ""
echo "1. ✅ Branches created and pushed automatically"
echo ""
echo "2. Create Production Infrastructure:"
echo "   • Go to: Actions → 'Create Production Infra'"
echo "   • Click 'Run workflow'"
echo "   • Type: CREATE-PROD"
echo "   • Wait ~15-20 minutes"
echo ""
echo "3. Create Testing Infrastructure:"
echo "   • Go to: Actions → 'Create Testing Infra'"
echo "   • Click 'Run workflow'"
echo "   • Type: CREATE"
echo "   • Wait ~10-15 minutes"
echo ""
echo "4. The following secrets will be AUTO-GENERATED"
echo "   (if PAT_TOKEN is set):"
echo "   • VITE_API_BASE_URL (from production CloudFront)"
echo "   • CORS_ALLOWED_ORIGINS (from production CloudFront)"
echo "   • DB_URL (from production RDS)"
echo "   • VITE_API_BASE_URL_TESTING (from testing CloudFront)"
echo "   • JWT_SECRET (auto-generated)"
echo ""
if [ "$set_pat" != "y" ] && [ "$set_pat" != "Y" ]; then
    echo "   ⚠️  Without PAT_TOKEN, you'll need to manually set these"
    echo "      secrets after infrastructure creation."
fi
echo ""
echo "5. Start developing!"
echo "   git checkout -b feature/my-feature"
echo "   # Make your changes"
echo "   git add ."
echo "   git commit -m \"Add new feature\""
echo "   git push origin feature/my-feature"
echo "   # CI/CD pipeline will automatically run!"
echo ""
echo "========================================="
echo "📚 DOCUMENTATION"
echo "========================================="
echo ""
echo "• Quick Start: QUICK_START_CICD.md"
echo "• Full Guide: CI_CD_WORKFLOW.md"
echo "• Admin Guide: ADMIN_CHECKLIST.md"
echo ""
echo "Happy deploying! 🚀"
